### ISSUE TITLE
When run make download, can not download feature.mat any more.

### ISSUE THREAD

**Issue by maoxiaofei99** [dangoron/diffusion#11]
Hi, when I test your code, the make download can not download all feature.mat any more? would you please share another link that I can download the mentioned features.mat and test all the code ?

Thank you very much, Je vous remerci !

**Comment by fyang93** [comment]
It looks like the INRIA's FTP service on that server is currently down or they just don't provide the resources anymore. Let's just wait for a couple of days, see if the situation will change. If not I may try to upload those files on google drive.

**Comment by maoxiaofei99** [comment]
Hi, sorry to ask again, but it will be very helpful to an fully understanding of your article if you could share a link for these feature.mat files. Thank you in advance.

**Comment by fyang93** [comment]
@maoxiaofei99 it seems the INRIA's server is alive now, please try running `make download` again :)

**Comment by vonhathanh** [comment]
@fyang93 The FTP service is really unstable at this time, can you upload these files somewhere else so we don't have to wait about a day-long to download. Thank you very much
![image](https://user-images.githubusercontent.com/20921387/78629663-e1c49700-78c1-11ea-920f-0b893fc27721.png)
