### ISSUE TITLE
Questions regarding Late Truncation

### ISSUE THREAD

**Issue by brianlan** [dangoron/diffusion#12]
Hi Fan, thanks for sharing and opening your code. And the code writing looks quite neat to me. 

After reading both of your paper and code, I got confused on __Late Truncation__. Would you please help me to understand it better? 

- I'm not sure which part of your code is actually implementing __Late Truncation__. By looking at [diffusion.py#L76-L78](https://github.com/fyang93/diffusion/blob/master/diffusion.py#L76-L78) and assuming we fix `use_ann = False`, it looks to me the normalization is processed after the graph truncation - `self.get_laplacian(sims[:, :kd], ids[:, :kd])` comes after `self.knn.search(self.features, n_trunc)`
- Another question is why we only select first `kd` neighbors `sims[:, :kd]` and `ids[:, :kd]` to form the affinity matrix rather than first `n_trunc`?

Thanks in advance.

**Comment by fyang93** [comment]
Hi, thank you for your interest in this project.

- Late truncation is applied here [diffusion.py#L23-L24](https://github.com/fyang93/diffusion/blob/master/diffusion.py#L23-L24). `self.knn.search(self.features, n_trunc)` is merely used to obtain the indices required for truncation in advance.
- `n_trunc` is used to determine a coarse range where the query's relevants could appear in. Or simply, it helps to rule out lots of true negatives. But many false positives are still in the first `n_trunc` results. While `kd` is the number of nearest neighbors linked by each node (image or feature) in the graph (affinity matrix), any link to false positives will possibly lead to wrong retrieval results. Usually, `kd` will be way smaller than `n_trunc`.

Hope this could help you :)

**Comment by fyang93** [comment]
Hi, thank you for your interest in this project.

- Late truncation is applied here [diffusion.py#L23-L24](https://github.com/fyang93/diffusion/blob/master/diffusion.py#L23-L24). `self.knn.search(self.features, n_trunc)` is merely used to obtain the indices required for truncation in advance.
- `n_trunc` is used to determine a coarse range where the query's relevants could appear in. Or simply, it helps to rule out lots of true negatives. But many false positives are still in the first `n_trunc` results. While `kd` is the number of nearest neighbors linked to each node (image or feature) in the graph (affinity matrix), any link to false positives will possibly lead to wrong retrieval results. Usually, `kd` will be way smaller than `n_trunc`.

Hope this could help you :)

**Comment by fyang93** [comment]
Hi, thank you for your interest in this project.

- Late truncation is applied here [diffusion.py#L23-L24](https://github.com/fyang93/diffusion/blob/master/diffusion.py#L23-L24). `self.knn.search(self.features, n_trunc)` is merely used to obtain the indices required for truncation in advance.
- `n_trunc` is used to determine a coarse range where the query's relevants could appear in. Or simply, it helps to rule out lots of true negatives. But many false positives are still in the first `n_trunc` results. While `kd` is the number of nearest neighbors linked to each node (image or feature) in the graph (affinity matrix), any link to false positives will possibly lead to wrong retrieval results. Usually, `kd` is way smaller than `n_trunc`.

Hope this could help you :)

**Comment by brianlan** [comment]
Thanks for your explanation, Fan. It's clear to me now. 

For the 2nd point, another way of understanding this just came to mind today. The reason we're using diffusion is that we assume data from different classes lies on different manifolds rather than in the same Euclidean Space. If `kd` is too large, it makes it more analogous to computing pair-wise distances in the Euclidean Space. So we need to keep `kd` to an appropriately smaller value, so that the distance between distant points are intrinsically obtained by accumulating distances from their neighbors in the middle. In other words, the similarity should only propagate through locally connected affinity graph. 

How does it sound?

**Comment by fyang93** [comment]
You got the point :)
It would be great if you can figure out how to set `kd` for each node in an adaptive way.
I'd like to close the issue if your problems are solved. Have a good day.
