### ISSUE TITLE
Running in  a custom dataset

### ISSUE THREAD

**Issue by Zumbalamambo** [dangoron/diffusion#13]
How do  I run this in a custom dataset containing a series of images?

**Comment by fyang93** [comment]
You may need to extract feature vectors for those images and then apply this method on them.
More specifically, you may want to save features in two matrices, containing queries and the gallery respectively.
Then just input them like [here](https://github.com/fyang93/diffusion/blob/master/rank.py#L30) and [here](https://github.com/fyang93/diffusion/blob/master/rank.py#L35).
