### ISSUE TITLE
Original source of features

### ISSUE THREAD

**Issue by bkj** [dangoron/diffusion#14]
Hi --

Can you point me to a paper that describes how the features you're downloading from `ftp://ftp.irisa.fr/local/texmex/corpus/diffusion/data` are computed?  In your paper, you mention you use the same features as Iscen et al, but I'm having trouble finding something the describes precisely how the model is trained / how the features are extracted.

Thanks!

**Comment by fyang93** [comment]
Sorry for replying lately.
The visual representation methods are developing really fast, so you don't have to stick with one of them.
The APLoss-based features should be the current [SOTA](https://github.com/almazan/deep-image-retrieval), pls take a look.
For the features you mentioned, you may refer to [R-MAC](https://github.com/gtolias/rmac) and [DIR](https://arxiv.org/abs/1610.07940).
Hope this helps.
