### ISSUE TITLE
Question about the evalution

### ISSUE THREAD

**Issue by trikim** [dangoron/diffusion#3]
你好，可以解释一下evaluation.py文件中的score_ap_from_ranks函数吗？感觉忽略了ranks的第一个值为非0的情况。

**Comment by fyang93** [comment]
evaluation的部分是另一个作者写的，我检查了一下好像你说得对，明天我替换成官方的Python实现 `https://github.com/filipradenovic/cnnimageretrieval-pytorch/blob/master/cirtorch/utils/evaluate.py`。不过实验中用的evaluation都是同一个文件，所以结果的对比是有效的。在现在的基础上还有另一种检索方式可以达到更好的mAP，明天一并更新吧

**Comment by fyang93** [comment]
@trikim 已修正，参考最新[commit](https://github.com/fyang93/diffusion/commit/f244c69eb6cd369d4dd7cf35dd5e18ca0f3855a1)

**Comment by trikim** [comment]
@fyang93 感谢
