### ISSUE TITLE
Where does the feature of a query come from?

### ISSUE THREAD

**Issue by gdjmck** [dangoron/diffusion#4]
In the paper, the input feature is 512 or 1024 dimension R-MAC descriptor, but in the downloaded data it is 2048 dimension, just like the last feature in resnet101.
Another question is that is resnet model just pretrained on ImageNet or other training data are used?
Thank you!

**Comment by fyang93** [comment]
@gdjmck, that could be a mistake. As far as I know, ResNet50 produces 2048-d descriptors at the last convolution layer.
As for the model, you may refer to [this paper](https://arxiv.org/abs/1604.02426) for further details, we only used their extracted descriptors.
