### ISSUE TITLE
Is it required for query features to be known when building Diffusion?

### ISSUE THREAD

**Issue by samehraban** [dangoron/diffusion#5]
Is it possible to use Diffusion for novel samples? in `rank.py` you passed `np.vstack([queries, gallery])` to `Diffusion`. So I wonder how to use it for novel samples?

**Comment by fyang93** [comment]
@samehraban, the current search function produces better performance. If you want to deal with unseen query samples you can check `search_old` function, which is the exact implementation of our paper.
