### ISSUE TITLE
Results in paper

### ISSUE THREAD

**Issue by bkj** [dangoron/diffusion#6]
I saw the other issue (#5) that points out that the current implementation assumes we know all of the queries as indexing time.  If I change `search` to `search_old` as suggested, and then run

```
make download
make mat2npy
make rank
```

I get 
```
>> oxford5k: mAP 91.33
```

Which cell in Table 1 of the paper does this correspond to?  I'm guessing it's the `w/o regional features + R-MAC (ResNet) + Oxf5K` -- is that right?  If so, do you know where the small loss in accuracy might be coming from?

**Comment by fyang93** [comment]
@bkj There was an issue in our evaluation code when we wrote the python code from the original matlab code (mentioned in #3), so the results become different after we switch to the official python implementation. We are sorry about that.
FYI, results in the paper were all evaluated by our previous evaluation code.
