### ISSUE TITLE
Example w/ regional features

### ISSUE THREAD

**Issue by bkj** [dangoron/diffusion#7]
Hi -- 

Can you give an example command to run your algorithm w/ regional features?  AFAICT the `Makefile` and code only show examples w/ global features, but perhaps I'm mistaken.

Thanks!
~ Ben

**Comment by fyang93** [comment]
The code for regional features is quite alike, most differences come from the IO part.
Since we want to make the published code simple and straightforward, if you are interested in the code for regional features, please contact me (yang at nii.ac.jp) to receive the code.
