### ISSUE TITLE
Request for your help

### ISSUE THREAD

**Issue by azmiara** [dangoron/diffusion#8]
1) Is it a good idea to try out your project with fashion datset ?
2) Could you please give a brief on what changes are required to modify for new dataset

**Comment by fyang93** [comment]
@azmiara
1. This method works on manifolds, it should be applicable if every fashion product has multiple instances that are enough to form a manifold. In my experience, the answer to your question is Yes.
2. For new datasets, you may need to extract features by yourself (a general recommendation is to use [Deep Image Retrieval](https://github.com/almazan/deep-image-retrieval)). You can then apply our method for subsequent searching.

**Comment by RichardTaoK** [comment]
can i know how do you get the  `oxford5k_resnet.mat`,Thank you ~

**Comment by fyang93** [comment]
> can i know how do you get the `oxford5k_resnet.mat`,Thank you ~

Please check `download` in `Makefile`. The `.mat` files are downloaded from [here](https://bit.ly/2kI7so5).
If you are interested in how those features are extracted, you may have to read the R-MAC paper.
