### ISSUE TITLE
how many retrievals are done per query in the Paris dataset?

### ISSUE THREAD

**Issue by surajitsaikia27** [dangoron/diffusion#9]
The results are very impressive with 0.97 mAP. Can you share how many retrievals are made to compute the mAP?

**Comment by fyang93** [comment]
> The results are very impressive with 0.97 mAP. Can you share how many retrievals are made to compute the mAP?

The Paris dataset has 55 queries and around 6k gallery images, so overall it requires 55*6k inner product operations to build the graph. But in practice, we used FAISS library to conduct k-NN search so the computation cost could be reduced.

**Comment by surajitsaikia27** [comment]
Hi, thank you so much for the reply. I want to ask one more thing.
How many top K retrievals you did to compute the mAP? For example, did you consider top 100 or top 10 retrievals to compute the mAP?

**Comment by fyang93** [comment]
@surajitsaikia27 If you have read our paper, you may notice the truncation process in our work. It decides the range in which the query can probe. Such a range is a union of `L` (the size of the truncated graph, or `n_trunc` in code) nearest neighbors of the query's `kq` nearest neighbors (kinda complex - -!), so at least we will get top-L retrieval results, and the rest gallery images are considered irrelevant to the query. But we still evaluate mAP on all gallery images by setting the similarities out of interest to zeros.
